# @package _global_
# Recipe: LoRA r=64, lr=2e-4, bucketing (28 buckets). Max_tokens=15000, num_workers=4.
model:
  perception:
    encoder:          # parakeet local attention (+/-128 frames each side)
        self_attention_model: rel_pos_local_attn
        att_context_size: [128, 128]
    rote:
      _target_: nemo.collections.speechlm2.modules.rote.RotaryTimeEmbedding
      dim: 1024
      rotary_fraction: 0.2
      theta: 1200.0

data:
  train_ds:
    num_workers: 4
    max_tokens: 16384
    min_duration: 0.1
    max_duration: 1200
    use_bucketing: true
    bucket_buffer_size: 20000
    num_buckets: 28
    bucket_duration_bins: [87,105,121,143,171,202,226,249,271,294,319,354,408,425,433,454,485,521,539,585,633,683,734,966,1545,3426,8832,16384]
    bucket_batch_size: [226,190,160,135,114,96,88,78,72,66,60,56,48,46,44,42,40,38,36,33,31,29,27,20,12,5,2,1]

exp_manager:
  checkpoint_callback_params:
    every_n_train_steps: 5000
