############ Model ############
model:
  pretrained_llm: meta-llama/Llama-3.2-1B-Instruct
  pretrained_asr: ${oc.env:SPEECH_ENCODER_MODEL}
  pretrained_weights: True  # When False, we use pretrained_name to load the architecture, but with random init

  freeze_params:
    # Frozen LLM
    - "^llm\\..+$"  # LLM
    - "^embed_tokens\\..+$"  # LLM embedding is moved
    # Frozen pretrained ASR (only the modality adapter layers are trainable)
    - "^perception\\.preprocessor\\..+$"
    - "^perception\\.encoder\\..+$"
  prevent_freeze_params: []  # Use to make specific submodules trainable; overrides freeze_params

  prompt_format: llama3
  audio_locator_tag: "<|audio|>"
  token_equivalent_duration: 0.08
  lora:
    task_type: CAUSAL_LM
    r: 128

  perception:
     target: nemo.collections.speechlm2.modules.perception.AudioPerceptionModule
     modality_adapter:
       _target_: nemo.collections.asr.modules.ConformerEncoder
       feat_in: 1024
       feat_out: -1 # you may set it if you need different output size other than the default d_model
       n_layers: 2
       d_model: 1024
       subsampling: dw_striding # vggnet, striding, stacking or stacking_norm, dw_striding
       subsampling_factor: 1 # must be power of 2 for striding and vggnet
       subsampling_conv_channels: 256 # set to -1 to make it equal to the d_model
       causal_downsampling: false
       ff_expansion_factor: 4
       self_attention_model: rel_pos # rel_pos or abs_pos
       n_heads: 8 # may need to be lower for smaller d_models
       # [left, right] specifies the number of steps to be seen from left and right of each step in self-attention
       att_context_size: [-1, -1]
       att_context_style: regular # regular or chunked_limited
       xscaling: true # scales up the input embeddings by sqrt(d_model)
       untie_biases: true # unties the biases of the TransformerXL layers
       pos_emb_max_len: 5000
       conv_kernel_size: 9
       conv_norm_type: batch_norm # batch_norm or layer_norm or groupnormN (N specifies the number of groups)
       # conv_context_size can be"causal" or a list of two integers while conv_context_size[0]+conv_context_size[1]+1==conv_kernel_size
       # null means [(kernel_size-1)//2, (kernel_size-1)//2], and 'causal' means [(kernel_size-1), 0]
       conv_context_size: null
       ### regularization
       dropout: 0 # The dropout used in most of the Conformer Modules
       dropout_pre_encoder: 0 # The dropout used before the encoder
       dropout_emb: 0.0 # The dropout used for embeddings
       dropout_att: 0 # The dropout for multi-headed attention modules

  optimizer:
    _target_: torch.optim.AdamW
    lr: 3e-4
    betas: [0.9, 0.98]
    weight_decay: 1e-3
    foreach: true # set to false if having issues with tensor-parallelism

  lr_scheduler:
    _target_: nemo.core.optim.lr_scheduler.CosineAnnealing
    warmup_steps: 250
    min_lr: 1e-6
    max_steps: ${trainer.max_steps}
    
trainer:
  devices: -1
  accelerator: gpu
  num_nodes: 1
  precision: bf16-true
  max_epochs: -1 
  # max_steps: 20
  limit_train_batches: 50_000  # number of steps in 1 epoch bc no epoch in lhotse
  accumulate_grad_batches: 4
  limit_val_batches: 0.0
  val_check_interval: 5000
  num_sanity_val_steps: 1
  sync_batchnorm: true
  log_every_n_steps: 5
  logger: false
  use_distributed_sampler: false
  enable_checkpointing: false
  gradient_clip_val: 1.0
  strategy:
    # Replace DDPStrategy with ModelParallelStrategy to enable model parallelism
    _target_: lightning.pytorch.strategies.DDPStrategy
    gradient_as_bucket_view: true
    find_unused_parameters: true
    # _target_: lightning.pytorch.strategies.ModelParallelStrategy
    # tensor_parallel_size: 2
    # data_parallel_size: 2

exp_manager:
  exp_dir: null
  #  explicit_log_dir: null
  name: test
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  use_datetime_version: false
  # max_time_per_run: 00:01:45:00
  max_time_per_run: 00:19:45:00

  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  # you need to set these two to True to continue the training
  resume_if_exists: true
  resume_ignore_no_checkpoint: true

  create_wandb_logger: false
  checkpoint_callback_params:
    filename: "{step:06.0f}"
    monitor: step
    mode: max
    every_n_train_steps: 5000
    every_n_epochs: null
    save_top_k: -1
    always_save_nemo: false
    save_nemo_on_train_end: false

############ Data ############
data:
  train_ds:
    sample_rate: 16000
    prompt_format: ${model.prompt_format}
    token_equivalent_duration: ${model.token_equivalent_duration}
    input_cfg:
      - type: group
        tags:
          lang: fr
          pnc: yes
          task: asr
        input_cfg:
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/FLEURS/manifest_FLEURS_casepunc_train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/Multilingual_LibriSpeech/manifest_Multilingual_LibriSpeech_recasepunc_train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/CommonVoice/manifest_CommonVoice_casepunc_train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/ACSYNT/manifest_ACSYNT_casepunc.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/CFPB/manifest_CFPB_recasepunc.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/CFPP2000/manifest_CFPP2000_recasepunc_train.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/AfricanAccentedFrench/manifest_AfricanAccentedFrench_recasepunc_max30_train.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/LVL-Atril-CTFAR/manifest_LVL-Atril-CTFAR_casepunc.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/YODAS/manifest_YODAS_casepunc_fr000.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/LVL-Atril-CTFNN1/manifest_LVL-Atril-CTFNN1_casepunc.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/OFROM/manifest_OFROM_recasepunc_train.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/PFC/manifest_PFC_casepunc.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/Multilingual_TEDx/manifest_Multilingual_TEDx_casepunc_train.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/VoxPopuli/manifest_VoxPopuli_casepunc_train.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/TCOF_Adultes/manifest_TCOF_Adultes_recasepunc_train.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # - type: multimodal_conversation
          #   manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/fr/context/TCOF_Enfants/manifest_TCOF_Enfants_recasepunc_train.jsonl
          #   audio_locator_tag: ${model.audio_locator_tag}
          # Missing youtube, PxSLU, SimSamu, Voxforge, Clapi, ESLO, Lesvocaux, linagora_meetings
        weight: 0.3
      - type: group
        tags:
          lang: en
          pnc: yes
          task: asr
        input_cfg:
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/en/context/CommonVoice/manifest_CommonVoice_casepunc_train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/asr/en/context/Yodas/manifest_Yodas.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
        weight: 0.3
      - type: group
        tags:
          lang: en
          pnc: yes
          task: qa
        input_cfg:
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-text-context/en/yijingwu--HeySQuAD_human/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/en/worstchan--UltraChat-300K-SLAM-Omni/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/en/liangtianle--unsafety-question/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/en/liangtianle--science-question/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/en/amuvarma--10k-filtered-tune-audio-text_answer/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/en/gruhit-patel--alpaca_speech_instruct/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/en/Menlo--instruction-speech-encodec-v1.5/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
        weight: 0.1
      - type: group
        tags:
          lang: fr
          pnc: yes
          task: qa
        input_cfg:
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-context-text-question/fr/VoxPopuli-QA/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/fr/CohereLabs--aya_collection/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/fr/ComparIA/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/question-answering/qa_audio-question-only/fr/Vigogne--Alpaca/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
        weight: 0.1
      - type: group
        tags:
          source_lang: fr
          target_lang: en
          pnc: yes
          task: ast
        input_cfg:
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/ast/fr-en/CoVoST/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
          - type: multimodal_conversation
            manifest_filepath: ${oc.env:DATA_FOLDER}/nemo/multi-turn/ast/fr-en/mTEDx/train.jsonl
            audio_locator_tag: ${model.audio_locator_tag}
        weight: 0.2
    seed: 42
    shuffle: true
    shard_seed: "randomized"
    text_field: 'answer'
    use_lhotse: true
    num_workers: 4

    max_duration: 90
    min_tokens: 2
    use_bucketing: false
    use_multimodal_sampling: true
    measure_total_length: true
    batch_tokens: 4096
    max_tokens: 2048


  validation_ds:
    prompt_format: ${model.prompt_format}
    token_equivalent_duration: ${model.token_equivalent_duration}
    datasets:
      CommonVoice_FR:  # rename to your dataset name, add more as needed
        input_cfg:
          - type: lhotse_as_conversation
            cuts_path: CommonVoice/cuts_CommonVoice_casepunc_dev.jsonl.gz
            audio_locator_tag: ${model.audio_locator_tag}
            tags:
              # Uncomment below line to include a system prompt.
              # system_prompt: "some system prompt"
              context: "Repeat after me, typing in lowercase."
    sample_rate: 16000
    batch_size: 32
    num_workers: 4
    seed: 42
    shard_seed: "randomized"